name: Build
on: [push, pull_request]
jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
            - name: Install dependencies
              run: npm ci
            - name: Generate ANTLR code
              run: npm run generate-antlr
            - name: Build
              run: npm run build
            - name: ESLint
              run: npm run eslint
            - name: Prettier lint
              run: npm run prettier-lint
            - name: Build in production mode
              run: npm run build-production
